const getters = {
    sidebar: state => state.app.sidebar,
    menuData:state => state.app.menuData,
    livenewsChannels: state => state.app.livenewsChannels,
    token: state => state.user.token,
    avatar: state => state.user.avatar,
    name: state => state.user.name,
    roleName: state => state.user.roleName,
    uid: state => state.user.uid,
    email: state => state.user.email,
    introduction: state => state.user.introduction,
    auth_type: state => state.user.auth_type,
    status: state => state.user.status,
    roles: state => state.user.roles,
    setting: state => state.user.setting,
    power: state => state.user.power,
    powerRead: state => state.user.powerRead,
    appRoles: state => state.admin.appRoles,
    parts: state => state.admin.parts,
    actions: state => state.admin.actions,
    compares: state => state.admin.compares,
    methods: state => state.admin.methods,
    variables: state => state.admin.variables,
    SSL: state => state.user.SSL,
    Main: state => state.user.Main,
    pcConnectNum: state => state.user.pcConnectNum,

    Pc: state => state.user.Pc,
    Mobile: state => state.user.Mobile,
    Enssl: state => state.user.Enssl,
    Enwas: state => state.user.Enwas,
    Charg: state => state.user.Charg,
    Log: state => state.user.Log,
    Ens2s: state => state.user.Ens2s,

    Ipsec: state => state.user.Ipsec,
    Dns: state => state.user.Dns,
    Firewall: state => state.user.Firewall,

    Haproxy: state => state.user.Haproxy,
    Terminal: state => state.user.Terminal,
};
export default getters
